### ISSUE TITLE
Codebereinigung: Stammesangehörigkeit 

### ISSUE THREAD

**Issue by SophZoe** [SophZoe/Genetic_Algorithm#24]
Stammesangehörigkeit soll nicht mehr in Toupeln abgespeichert werden

**Comment by Salt-is-leaving** [comment]
#5 , weil wir 3 schon hatten.

GENPOOL = {
    "Gene": {
        "Kondition": (1, 5),  # Erweiterter Bereich
        "Sichtweite": (1, 5),  # Erweiterter Bereich
        "Geschwindigkeit": (1, 5),  # Neues Gen
        "Intelligenz": (1, 5),  # Neues Gen
    },
    "Stämme": {
        1: {"Bevorzugtes Gen": "Geschwindigkeit", "Modifikator": 1.2},
        2: {"Bevorzugtes Gen": "Sichtweite", "Modifikator": 1.2},
        3: {"Bevorzugtes Gen": "Intelligenz", "Modifikator": 1.2},
    }
}
