### ISSUE TITLE
Track number of "birthed agents", "perished agents" and placed food per round

### ISSUE THREAD

**Issue by SophZoe** [SophZoe/Genetic_Algorithm#39]
Create a counter and an output for every new and vanished item/agent per round.

**Comment by Markomrnkvc** [comment]
do you want it to be a counter which gets written into the csv or just as an output?

A counter for perished Agents already exists i think as "deceased counter"

**Comment by SophZoe** [comment]
we want it to be like a counter in the backround for every single thing that is changing during each round of the simulation. It's not going to display an output for every single round normally, but it's purpose would be, to be something that would be callable if needed, for example to support the visualisation with exact numbers of what happened during that round.

**Comment by Jxshyz** [comment]
Please note that the print output for world 1 and world 2 isn't quite accurate. 

The output won't show the exact number of agents died per world
