### ISSUE TITLE
need to solve: two main.py files

### ISSUE THREAD

**Issue by julietteyek** [SophZoe/Genetic_Algorithm#45]
Nach dem merge (visualization->main) bei dir, Marko, kam die alte Ordnerstruktur zurück:

die aktualisierte main.py mit der visualization ist jetzt in
"pytest-Genetic_Algorithm/MAINCODE/main.py"

statt in
"MAINCODE/main.py"

bitte beide main.py vergleichen und die aktuelle behalten und in den MAINCODE Ordner schieben (pytest-Genetic_Algorithm Ordner löschen)

**Comment by Markomrnkvc** [comment]
just merged everything :))))
