### ISSUE TITLE
Overview/Implement ParamGrid for the world

### ISSUE THREAD

**Issue by SophZoe** [SophZoe/Genetic_Algorithm#48]
create  list of dictionaries where each dictionary equals one world. Take a deeper look at how to implement them in a practical way. Add useful weights for different food spawn rates. Maybe try adding different kinds of food.

**Comment by julietteyek** [comment]
food-energy should change with every food-spawning
// or //
food should spawn in different rates

**Comment by Jxshyz** [comment]
Idea for different worlds:
- One world could contain many toxic foods and thus favor intelligent creatures that ignore toxic foods.
- A second world could contain hardly any poisonous food and thus give aggressive creatures an advantage

**Comment by Markomrnkvc** [comment]
how about a world with designated spaces where food can spawn (and only there)?
could be interesting in world with aggresiv agents or overcrowded worlds =)
