### ISSUE TITLE
config visualization to make intelligent and aggressive agents distinguishable 

### ISSUE THREAD

**Issue by Jxshyz** [SophZoe/Genetic_Algorithm#60]
intelligent agents as blue, aggressive agents as red dots

**Comment by Markomrnkvc** [comment]
I can add an extra mode which shows wether the last agent added to the board is intelligent or agressiv, the problem is how to implement it when we want to see it like a heatmap as it gets messy

Any Ideas?

**Comment by Jxshyz** [comment]
That's a good point 💡

We could perhaps reduce the opacity of the individual dots and choose a color for the logical pair Intelligent/Aggressive that in combination results in a third, distinguishable color (e.g. red and blue = purple).
For the poisonous & non-poisonous food I suggest yellow and green.

What do you think of this suggestion?
